/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryofusIndexRouteImport } from './routes/storyofus.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoryofusTrackOrderRouteImport } from './routes/storyofus.track-order'
import { Route as StoryofusSetupRouteImport } from './routes/storyofus.setup'
import { Route as StoryofusRefundPolicyRouteImport } from './routes/storyofus.refund-policy'
import { Route as StoryofusDemoRouteImport } from './routes/storyofus.demo'
import { Route as StoryofusCheckoutRouteImport } from './routes/storyofus.checkout'
import { Route as SektorSlugRouteImport } from './routes/sektor.$slug'
import { Route as DemoMiraCafeRouteImport } from './routes/demo.mira-cafe'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminStoryofusOrdersRouteImport } from './routes/admin.storyofus-orders'
import { Route as StoryofusStylesStyleRouteImport } from './routes/storyofus.styles.$style'
import { Route as StoryofusSetupDemoRouteImport } from './routes/storyofus.setup.demo'
import { Route as ApiStoryofusShopierCallbackRouteImport } from './routes/api.storyofus.shopier.callback'
import { Route as ApiInternalStoryofusReviewReadyWorkerRouteImport } from './routes/api.internal.storyofus.review-ready-worker'
import { Route as ApiInternalStoryofusEmailWorkerRouteImport } from './routes/api.internal.storyofus.email-worker'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryofusIndexRoute = StoryofusIndexRouteImport.update({
  id: '/storyofus/',
  path: '/storyofus/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoryofusTrackOrderRoute = StoryofusTrackOrderRouteImport.update({
  id: '/storyofus/track-order',
  path: '/storyofus/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryofusSetupRoute = StoryofusSetupRouteImport.update({
  id: '/storyofus/setup',
  path: '/storyofus/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryofusRefundPolicyRoute = StoryofusRefundPolicyRouteImport.update({
  id: '/storyofus/refund-policy',
  path: '/storyofus/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryofusDemoRoute = StoryofusDemoRouteImport.update({
  id: '/storyofus/demo',
  path: '/storyofus/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryofusCheckoutRoute = StoryofusCheckoutRouteImport.update({
  id: '/storyofus/checkout',
  path: '/storyofus/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SektorSlugRoute = SektorSlugRouteImport.update({
  id: '/sektor/$slug',
  path: '/sektor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMiraCafeRoute = DemoMiraCafeRouteImport.update({
  id: '/demo/mira-cafe',
  path: '/demo/mira-cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoryofusOrdersRoute = AdminStoryofusOrdersRouteImport.update({
  id: '/storyofus-orders',
  path: '/storyofus-orders',
  getParentRoute: () => AdminRoute,
} as any)
const StoryofusStylesStyleRoute = StoryofusStylesStyleRouteImport.update({
  id: '/storyofus/styles/$style',
  path: '/storyofus/styles/$style',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryofusSetupDemoRoute = StoryofusSetupDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => StoryofusSetupRoute,
} as any)
const ApiStoryofusShopierCallbackRoute =
  ApiStoryofusShopierCallbackRouteImport.update({
    id: '/api/storyofus/shopier/callback',
    path: '/api/storyofus/shopier/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalStoryofusReviewReadyWorkerRoute =
  ApiInternalStoryofusReviewReadyWorkerRouteImport.update({
    id: '/api/internal/storyofus/review-ready-worker',
    path: '/api/internal/storyofus/review-ready-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalStoryofusEmailWorkerRoute =
  ApiInternalStoryofusEmailWorkerRouteImport.update({
    id: '/api/internal/storyofus/email-worker',
    path: '/api/internal/storyofus/email-worker',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kvkk': typeof KvkkRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/storyofus-orders': typeof AdminStoryofusOrdersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/demo/mira-cafe': typeof DemoMiraCafeRoute
  '/sektor/$slug': typeof SektorSlugRoute
  '/storyofus/checkout': typeof StoryofusCheckoutRoute
  '/storyofus/demo': typeof StoryofusDemoRoute
  '/storyofus/refund-policy': typeof StoryofusRefundPolicyRoute
  '/storyofus/setup': typeof StoryofusSetupRouteWithChildren
  '/storyofus/track-order': typeof StoryofusTrackOrderRoute
  '/admin/': typeof AdminIndexRoute
  '/storyofus/': typeof StoryofusIndexRoute
  '/storyofus/setup/demo': typeof StoryofusSetupDemoRoute
  '/storyofus/styles/$style': typeof StoryofusStylesStyleRoute
  '/api/internal/storyofus/email-worker': typeof ApiInternalStoryofusEmailWorkerRoute
  '/api/internal/storyofus/review-ready-worker': typeof ApiInternalStoryofusReviewReadyWorkerRoute
  '/api/storyofus/shopier/callback': typeof ApiStoryofusShopierCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kvkk': typeof KvkkRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/storyofus-orders': typeof AdminStoryofusOrdersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/demo/mira-cafe': typeof DemoMiraCafeRoute
  '/sektor/$slug': typeof SektorSlugRoute
  '/storyofus/checkout': typeof StoryofusCheckoutRoute
  '/storyofus/demo': typeof StoryofusDemoRoute
  '/storyofus/refund-policy': typeof StoryofusRefundPolicyRoute
  '/storyofus/setup': typeof StoryofusSetupRouteWithChildren
  '/storyofus/track-order': typeof StoryofusTrackOrderRoute
  '/admin': typeof AdminIndexRoute
  '/storyofus': typeof StoryofusIndexRoute
  '/storyofus/setup/demo': typeof StoryofusSetupDemoRoute
  '/storyofus/styles/$style': typeof StoryofusStylesStyleRoute
  '/api/internal/storyofus/email-worker': typeof ApiInternalStoryofusEmailWorkerRoute
  '/api/internal/storyofus/review-ready-worker': typeof ApiInternalStoryofusReviewReadyWorkerRoute
  '/api/storyofus/shopier/callback': typeof ApiStoryofusShopierCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kvkk': typeof KvkkRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/storyofus-orders': typeof AdminStoryofusOrdersRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/demo/mira-cafe': typeof DemoMiraCafeRoute
  '/sektor/$slug': typeof SektorSlugRoute
  '/storyofus/checkout': typeof StoryofusCheckoutRoute
  '/storyofus/demo': typeof StoryofusDemoRoute
  '/storyofus/refund-policy': typeof StoryofusRefundPolicyRoute
  '/storyofus/setup': typeof StoryofusSetupRouteWithChildren
  '/storyofus/track-order': typeof StoryofusTrackOrderRoute
  '/admin/': typeof AdminIndexRoute
  '/storyofus/': typeof StoryofusIndexRoute
  '/storyofus/setup/demo': typeof StoryofusSetupDemoRoute
  '/storyofus/styles/$style': typeof StoryofusStylesStyleRoute
  '/api/internal/storyofus/email-worker': typeof ApiInternalStoryofusEmailWorkerRoute
  '/api/internal/storyofus/review-ready-worker': typeof ApiInternalStoryofusReviewReadyWorkerRoute
  '/api/storyofus/shopier/callback': typeof ApiStoryofusShopierCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kvkk'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/admin/storyofus-orders'
    | '/admin/tasks'
    | '/demo/mira-cafe'
    | '/sektor/$slug'
    | '/storyofus/checkout'
    | '/storyofus/demo'
    | '/storyofus/refund-policy'
    | '/storyofus/setup'
    | '/storyofus/track-order'
    | '/admin/'
    | '/storyofus/'
    | '/storyofus/setup/demo'
    | '/storyofus/styles/$style'
    | '/api/internal/storyofus/email-worker'
    | '/api/internal/storyofus/review-ready-worker'
    | '/api/storyofus/shopier/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kvkk'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/admin/storyofus-orders'
    | '/admin/tasks'
    | '/demo/mira-cafe'
    | '/sektor/$slug'
    | '/storyofus/checkout'
    | '/storyofus/demo'
    | '/storyofus/refund-policy'
    | '/storyofus/setup'
    | '/storyofus/track-order'
    | '/admin'
    | '/storyofus'
    | '/storyofus/setup/demo'
    | '/storyofus/styles/$style'
    | '/api/internal/storyofus/email-worker'
    | '/api/internal/storyofus/review-ready-worker'
    | '/api/storyofus/shopier/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kvkk'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/admin/storyofus-orders'
    | '/admin/tasks'
    | '/demo/mira-cafe'
    | '/sektor/$slug'
    | '/storyofus/checkout'
    | '/storyofus/demo'
    | '/storyofus/refund-policy'
    | '/storyofus/setup'
    | '/storyofus/track-order'
    | '/admin/'
    | '/storyofus/'
    | '/storyofus/setup/demo'
    | '/storyofus/styles/$style'
    | '/api/internal/storyofus/email-worker'
    | '/api/internal/storyofus/review-ready-worker'
    | '/api/storyofus/shopier/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KvkkRoute: typeof KvkkRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DemoMiraCafeRoute: typeof DemoMiraCafeRoute
  SektorSlugRoute: typeof SektorSlugRoute
  StoryofusCheckoutRoute: typeof StoryofusCheckoutRoute
  StoryofusDemoRoute: typeof StoryofusDemoRoute
  StoryofusRefundPolicyRoute: typeof StoryofusRefundPolicyRoute
  StoryofusSetupRoute: typeof StoryofusSetupRouteWithChildren
  StoryofusTrackOrderRoute: typeof StoryofusTrackOrderRoute
  StoryofusIndexRoute: typeof StoryofusIndexRoute
  StoryofusStylesStyleRoute: typeof StoryofusStylesStyleRoute
  ApiInternalStoryofusEmailWorkerRoute: typeof ApiInternalStoryofusEmailWorkerRoute
  ApiInternalStoryofusReviewReadyWorkerRoute: typeof ApiInternalStoryofusReviewReadyWorkerRoute
  ApiStoryofusShopierCallbackRoute: typeof ApiStoryofusShopierCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyofus/': {
      id: '/storyofus/'
      path: '/storyofus'
      fullPath: '/storyofus/'
      preLoaderRoute: typeof StoryofusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/storyofus/track-order': {
      id: '/storyofus/track-order'
      path: '/storyofus/track-order'
      fullPath: '/storyofus/track-order'
      preLoaderRoute: typeof StoryofusTrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyofus/setup': {
      id: '/storyofus/setup'
      path: '/storyofus/setup'
      fullPath: '/storyofus/setup'
      preLoaderRoute: typeof StoryofusSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyofus/refund-policy': {
      id: '/storyofus/refund-policy'
      path: '/storyofus/refund-policy'
      fullPath: '/storyofus/refund-policy'
      preLoaderRoute: typeof StoryofusRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyofus/demo': {
      id: '/storyofus/demo'
      path: '/storyofus/demo'
      fullPath: '/storyofus/demo'
      preLoaderRoute: typeof StoryofusDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyofus/checkout': {
      id: '/storyofus/checkout'
      path: '/storyofus/checkout'
      fullPath: '/storyofus/checkout'
      preLoaderRoute: typeof StoryofusCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sektor/$slug': {
      id: '/sektor/$slug'
      path: '/sektor/$slug'
      fullPath: '/sektor/$slug'
      preLoaderRoute: typeof SektorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mira-cafe': {
      id: '/demo/mira-cafe'
      path: '/demo/mira-cafe'
      fullPath: '/demo/mira-cafe'
      preLoaderRoute: typeof DemoMiraCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storyofus-orders': {
      id: '/admin/storyofus-orders'
      path: '/storyofus-orders'
      fullPath: '/admin/storyofus-orders'
      preLoaderRoute: typeof AdminStoryofusOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/storyofus/styles/$style': {
      id: '/storyofus/styles/$style'
      path: '/storyofus/styles/$style'
      fullPath: '/storyofus/styles/$style'
      preLoaderRoute: typeof StoryofusStylesStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyofus/setup/demo': {
      id: '/storyofus/setup/demo'
      path: '/demo'
      fullPath: '/storyofus/setup/demo'
      preLoaderRoute: typeof StoryofusSetupDemoRouteImport
      parentRoute: typeof StoryofusSetupRoute
    }
    '/api/storyofus/shopier/callback': {
      id: '/api/storyofus/shopier/callback'
      path: '/api/storyofus/shopier/callback'
      fullPath: '/api/storyofus/shopier/callback'
      preLoaderRoute: typeof ApiStoryofusShopierCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/storyofus/review-ready-worker': {
      id: '/api/internal/storyofus/review-ready-worker'
      path: '/api/internal/storyofus/review-ready-worker'
      fullPath: '/api/internal/storyofus/review-ready-worker'
      preLoaderRoute: typeof ApiInternalStoryofusReviewReadyWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/storyofus/email-worker': {
      id: '/api/internal/storyofus/email-worker'
      path: '/api/internal/storyofus/email-worker'
      fullPath: '/api/internal/storyofus/email-worker'
      preLoaderRoute: typeof ApiInternalStoryofusEmailWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminStoryofusOrdersRoute: typeof AdminStoryofusOrdersRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStoryofusOrdersRoute: AdminStoryofusOrdersRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoryofusSetupRouteChildren {
  StoryofusSetupDemoRoute: typeof StoryofusSetupDemoRoute
}

const StoryofusSetupRouteChildren: StoryofusSetupRouteChildren = {
  StoryofusSetupDemoRoute: StoryofusSetupDemoRoute,
}

const StoryofusSetupRouteWithChildren = StoryofusSetupRoute._addFileChildren(
  StoryofusSetupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KvkkRoute: KvkkRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DemoMiraCafeRoute: DemoMiraCafeRoute,
  SektorSlugRoute: SektorSlugRoute,
  StoryofusCheckoutRoute: StoryofusCheckoutRoute,
  StoryofusDemoRoute: StoryofusDemoRoute,
  StoryofusRefundPolicyRoute: StoryofusRefundPolicyRoute,
  StoryofusSetupRoute: StoryofusSetupRouteWithChildren,
  StoryofusTrackOrderRoute: StoryofusTrackOrderRoute,
  StoryofusIndexRoute: StoryofusIndexRoute,
  StoryofusStylesStyleRoute: StoryofusStylesStyleRoute,
  ApiInternalStoryofusEmailWorkerRoute: ApiInternalStoryofusEmailWorkerRoute,
  ApiInternalStoryofusReviewReadyWorkerRoute:
    ApiInternalStoryofusReviewReadyWorkerRoute,
  ApiStoryofusShopierCallbackRoute: ApiStoryofusShopierCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
